baseURL = "https://sarafecadu.github.io/blog/"
relativeURLs = "false"
languageCode = "en-us"
title = "Sara Fecadu"
theme = "minimal"
publishDir = "docs"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "Sara Fecadu"
    description = "A blog for technical wonderings"
    githubUsername = "sarafecadu"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "javascript", "rust", "sql", "bash"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/sarafecadu"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/sarafecadu"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/sara-fecadu"
    name = "linkedin"
    weight = 3
